# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_sans_accents', models.CharField(blank=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('movements', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('sex', models.CharField(blank=True, max_length=255)),
                ('born', models.CharField(blank=True, max_length=255)),
                ('died', models.CharField(blank=True, max_length=255)),
                ('descriptors', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_sans_accents', models.CharField(blank=True, max_length=255)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('medium', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dimensions', models.CharField(max_length=300)),
                ('pageurl', models.CharField(max_length=255)),
                ('accession_number', models.CharField(blank=True, max_length=255)),
                ('imageurl', models.CharField(max_length=255)),
                ('timestamp', models.DateField(null=True)),
                ('collection', models.CharField(blank=True, max_length=255)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('meta', models.TextField(blank=True)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Artwork')),
                ('collection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastCrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spider_name', models.CharField(max_length=255)),
                ('last_crawled', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NameVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=255)),
                ('nation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ethnicity'),
        ),
        migrations.AddField(
            model_name='artist',
            name='movement',
            field=models.ManyToManyField(blank=True, to='app.Movement'),
        ),
        migrations.AddField(
            model_name='artist',
            name='new_nationality',
            field=models.ManyToManyField(blank=True, to='app.Nationality'),
        ),
    ]
