# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-28 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('medium', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dimensions', models.CharField(max_length=255)),
                ('collection', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
                ('pageurl', models.CharField(max_length=255)),
                ('imageurl', models.CharField(max_length=255)),
                ('scrapedate', models.CharField(max_length=255)),
            ],
        ),
    ]
