# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pageurl', models.CharField(max_length=255)),
                ('imageurl', models.CharField(max_length=255)),
                ('timestamp', models.DateField(null=True)),
                ('collection', models.CharField(blank=True, max_length=255)),
                ('artist', models.ManyToManyField(blank=True, to='app.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='display',
            name='exhibition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Exhibition'),
        ),
    ]
