# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
