# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161213_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('artist_sans_accents', models.CharField(blank=True, max_length=255)),
                ('movements', models.CharField(blank=True, max_length=255)),
                ('sex', models.CharField(blank=True, max_length=255)),
                ('born', models.CharField(blank=True, max_length=255)),
                ('died', models.CharField(blank=True, max_length=255)),
                ('descriptors', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(blank=True, max_length=255)),
                ('collection_address', models.CharField(blank=True, max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('meta', models.TextField(blank=True)),
            ],
        ),
    ]
