# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_artwork_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
