# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170406_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='artwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Artwork'),
        ),
        migrations.AlterField(
            model_name='display',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Exhibition'),
        ),
    ]
