# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 03:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170407_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['artist']},
        ),
    ]
