# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161213_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Artist'),
        ),
    ]
