# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170409_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={},
        ),
    ]
