# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-06 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161105_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
