# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161106_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='scrapedate',
        ),
    ]
