# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_artwork_scrapedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artist_sans_accents',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='title_sans_accents',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
