# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_artwork_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='artist_link',
            new_name='artist',
        ),
    ]
