# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20161110_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='born',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='descriptors',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='died',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='movements',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='nationality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artwork',
            name='sex',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
