# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161110_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
