# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161219_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='collection',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
