# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='queued_artworks',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='viewed_artworks',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='queued_artwork',
            field=models.ManyToManyField(blank=True, related_name='queued', to='app.Artwork'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='viewed_artwork',
            field=models.ManyToManyField(blank=True, related_name='viewed', to='app.Artwork'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_artist',
            field=models.ManyToManyField(blank=True, to='app.Artist'),
        ),
    ]
