# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170418_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_artist',
            field=models.ManyToManyField(blank=True, related_name='favorite_artist', to='app.Artist'),
        ),
    ]
