# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-08 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20161123_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='accession_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
