# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-19 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170419_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_artist',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='queued_artwork',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='viewed_artwork',
        ),
    ]
