# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20161219_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='movements',
        ),
    ]
