# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 23:25
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20161219_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_variants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
