# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 23:30
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_artist_artist_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_sans_accents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=600), blank=True, null=True, size=None),
        ),
    ]
