# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20161220_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_variants',
        ),
    ]
