# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 00:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_artist_artist_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistNameVariants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Artist')),
            ],
        ),
    ]
