# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_artistnamevariants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArtistNameVariants',
            new_name='Name_Variant',
        ),
    ]
