# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20161221_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(max_length=255)),
                ('artists', models.ManyToManyField(null=True, to='app.Artist')),
            ],
        ),
    ]
