# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
