# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20161221_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='artists',
            field=models.ManyToManyField(blank=True, to='app.Artist'),
        ),
    ]
