# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20161221_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='artists',
        ),
        migrations.AddField(
            model_name='artist',
            name='movement',
            field=models.ManyToManyField(blank=True, to='app.Movement'),
        ),
    ]
