# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-21 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20161221_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnicity', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Ethnicity'),
        ),
        migrations.AddField(
            model_name='artist',
            name='new_nationality',
            field=models.ManyToManyField(blank=True, to='app.Nationality'),
        ),
    ]
