# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-22 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20161221_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name_Variant',
            new_name='NameVariant',
        ),
    ]
