# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20161222_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
