# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20161222_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='descrtiption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='nationality',
            field=models.CharField(max_length=255),
        ),
    ]
