# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-29 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20161229_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='descrtiption',
            new_name='description',
        ),
    ]
