# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_artist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
